### ISSUE TITLE
Is there a reason to create the first record in the 'drink' table in models.py?

### ISSUE THREAD

**Issue by Frodriguez9** [udacity/FSND#129]
When I run the flask app, I get a "NameError: Name 'drink' is not defined" coming from the models.py.

Is there a reason to define "drink" inside the db_drop_and_create_all() function in models.py ??

models.py

```
def db_drop_and_create_all():    
    db.drop_all()    
    db.create_all()    
    # add one demo row which is helping in POSTMAN test    
    drink = Drink(        
            title='water',        
            recipe='[{"name": "water", "color": "blue", "parts": 1}]'  
  )

drink.insert()
```

In my local machine, I moved the "drink" variable and its insertion to the database to api.py after calling db_drop_and_create_all() and the app ran without crashing.

api.py
```
app = Flask(__name__)
setup_db(app)
CORS(app)

db_drop_and_create_all()

drink = Drink(
    title='water',
    recipe='[{"name": "water", "color": "blue", "parts": 1}]'
    )

drink.insert()
```

**Comment by SudKul** [comment]
Hi @Frodriguez9 
In the starter code, the following declaration inside of the `db_drop_and_create_all()` function has its **scope limited within the function.** 
```
drink = Drink(        
            title='water',        
            recipe='[{"name": "water", "color": "blue", "parts": 1}]' 
```
The line above resets the database and adds one demo row to help in POSTMAN test. 


Whereas, when you run the code, it will throw the error you've mentioned due to the `drink.insert()` line. Here, `drink` is an instance of the Drink class which has not been defined yet. 

Feel free to discuss more on our [Knowledge platform. ](https://knowledge.udacity.com/)
Happy learning.
