### ISSUE TITLE
Wrong way of Unpacking Dict Object

### ISSUE THREAD

**Issue by DataPsycho** [udacity/FSND#32]
Hi, can you check that line:
https://github.com/udacity/FSND/blob/master/projects/03_coffee_shop_full_stack/starter_code/backend/src/database/models.py#L51

after json dump now the result is a dict object. So we should use `key, value, dict.items()` if we really want to unpack a dict into a list. Not sure If I am missing something.

**Comment by SudKul** [comment]
Hi @DataPsycho 
The `json.dumps()` actually generates a string (instead of a dict object, as perceived by you). On the other hand, the `json.loads()` is creating (dictionary) object for us.
 
In the [line you've mentioned](https://github.com/udacity/FSND/blob/master/projects/03_coffee_shop_full_stack/starter_code/backend/src/database/models.py#L51), the steps are
1. The `json.loads(self.recipe)` will create a list of dictionary objects. It will now be formatted as:
```json
[
	{
		"name" : "milk",
		"color": "grey",
		"parts": 1
	},
	{
		"name" : "matcha",
		"color": "green",
		"parts": 3
	}
]
```
2. Therefore `for r in json.loads(self.recipe)` will iterate over the dictionary objects. Here, `r` is an individual object within the list, each having `name`, `color`, and `parts` . Thus, `r['color'] ` will fetch the value.

For more details, feel free to raise your concern on the Knowledge hub, so that newer students too can learn from the discussion.
 
Thank you.
