### ISSUE TITLE
The button label in the Add new artist form says Create Venue.

### ISSUE THREAD

**Issue by Ofineo** [udacity/FSND#35]
The button label in the Add new artist form says Create Venue.

` <input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">`

I can change it if you don't mind me

**Comment by fastalana** [comment]
I noticed this is also the case for shows on the form - FSND/projects/01_fyyur/starter_code/templates/forms/new_show.html
Instead of:
`<input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">`
It should be:
`<input type="submit" value="Create Shows" class="btn btn-primary btn-lg btn-block">`

From what I can tell, there 10 open PRs as old as November 2019.  It's possible that they aren't monitoring this repo regularly.

**Comment by SudKul** [comment]
This has now been fixed. 
Thanks, @fastalana and @Ofineo
